#!/bin/bash

set -euo pipefail

datasette publish fly notebook.db \
  --app notebook-schu-io \
  --metadata metadata.yaml \
  --install datasette-template-sql \
  --install "datasette-sitemap>=1.0" \
  --install "datasette-atom>=0.7" \
  --install datasette-json-html \
  --install beautifulsoup4 \
  --install "datasette-debug-asgi>=1.1" \
  --install "datasette-graphql>=2.2" \
  --install datasette-block-robots \
  --plugins-dir plugins \
  --template-dir templates
